#!/bin/sh /etc/rc.common
GATEWAY_IP=192.168.0.201
PORT=8082

start() {
	start-stop-daemon -S -b -q -x /usr/bin/luci-splashd $PORT $GATEWAY_IP 
	iptables -t nat -A PREROUTING -d $GATEWAY_IP -j ACCEPT
	iptables -t nat -A PREROUTING -p tcp -d ! $GATEWAY_IP --dport 80 -j DNAT --to-destination $GATEWAY_IP:$PORT 
}

stop() {
	echo "stop"
	iptables -t nat -F
}
